### ISSUE TITLE
2022: Search 

### ISSUE THREAD

**Issue by nanorepublica** [thec3uk/new_to_church#47]
Using Algolia for search.

## todo

* [ ] Search results list UI & UX, layout and styling
* [ ] Index the correct data and configure each individual hit

## nice to have
* [ ] Separate search page? (view all results)
* [ ] Pull from multiple indexes (teaching series & other sites when they have search)
