### ISSUE TITLE
Teaching Series

### ISSUE THREAD

**Issue by nanorepublica** [thec3uk/new_to_church#48]
This is in a separate repo

* Do layout and styling (mobile & desktop)
* Convert to Tailwind
* Start creating C3 component library to share react components across the site.

**Comment by nanorepublica** [comment]
## todo

* Review teaching site code.
* Give access to Phil for content
* Copy out components to begin with?
* Convert stuff to tailwind?

**Comment by nanorepublica** [comment]
Routes to convert:
* [ ] index
* [ ] messages index
* [ ] messages detail
* [ ] series index
* [ ] series detail
* [ ] speaker index
* [ ] speaker detail
* [ ] channel index
* [ ] channel detail

**Comment by nanorepublica** [comment]
* [ ]  Search in the nav just a link to /messages for now

**Comment by nanorepublica** [comment]
* [ ] infinite hits customisation...

**Comment by nanorepublica** [comment]
* [ ] hover state for playing needs to be hoisted to across the search results

**Comment by nanorepublica** [comment]
* [ ] mobile layout for search page

**Comment by nanorepublica** [comment]
* [ ] footer links
* [ ] hero links that are too long on mobile
